In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":['harry', 'rohan','Nikhil','Amruta'],
    "marks" :[92, 34, 24, 99],
    "city" :['rampur', 'kolkata', 'bareilly', 'antarctica']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks        city
0   harry     92      rampur
1   rohan     34     kolkata
2  Nikhil     24    bareilly
3  Amruta     99  antarctica

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_index_false.csv', index = False)

In [7]:
df.head(2)

    name  marks     city
0  harry     92   rampur
1  rohan     34  kolkata

In [8]:
df.tail(1)

     name  marks        city
3  Amruta     99  antarctica

In [9]:
df.describe()

           marks
count   4.000000
mean   62.250000
std    38.715845
min    24.000000
25%    31.500000
50%    63.000000
75%    93.750000
max    99.000000

In [10]:
df.index = ['first', 'second','third', 'fourth']

In [11]:
df

          name  marks        city
first    harry     92      rampur
second   rohan     34     kolkata
third   Nikhil     24    bareilly
fourth  Amruta     99  antarctica

In [12]:
ser = pd.Series(np.random.rand(32))

In [13]:
ser

0     0.704625
1     0.405928
2     0.834374
3     0.812266
4     0.720808
5     0.304230
6     0.723546
7     0.989144
8     0.674356
9     0.218436
10    0.741447
11    0.404385
12    0.429745
13    0.323254
14    0.537500
15    0.573669
16    0.234083
17    0.850628
18    0.905441
19    0.248453
20    0.251085
21    0.669447
22    0.523897
23    0.793944
24    0.854192
25    0.146323
26    0.715249
27    0.076916
28    0.586205
29    0.329318
30    0.720087
31    0.118789
dtype: float64

In [14]:
type(ser)

pandas.core.series.Series

In [15]:
newdf = pd.DataFrame(np.random.rand(334, 5), index = np.arange(334))

In [16]:
newdf

            0         1         2         3         4
0    0.681765  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [17]:
type(newdf)

pandas.core.frame.DataFrame

In [18]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.502063    0.495273    0.490358    0.476386    0.507589
std      0.280018    0.277697    0.281980    0.287601    0.294077
min      0.000391    0.000622    0.000099    0.001491    0.004628
25%      0.264461    0.257474    0.247936    0.224820    0.242713
50%      0.489666    0.491745    0.488040    0.443153    0.531335
75%      0.721223    0.722597    0.744890    0.740297    0.751304
max      0.994718    0.995151    0.999106    0.998734    0.998132

In [19]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [20]:
newdf[0][0] = "Harry"

In [21]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.head

<bound method NDFrame.head of             0         1         2         3         4
0       Harry  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]>

In [23]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int32', length=334)

In [24]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [25]:
newdf.to_numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0       Harry  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]>

In [26]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,Harry,0.471677,0.647117,0.397568,0.562236,0.226655,0.719953,0.552616,0.472986,0.262193,...,0.620154,0.135762,0.718943,0.785621,0.581591,0.994718,0.912063,0.161824,0.862252,0.387462
1,0.794984,0.396226,0.400476,0.782624,0.487736,0.460376,0.666812,0.718526,0.508215,0.253001,...,0.107586,0.278809,0.195752,0.304188,0.189906,0.552123,0.61481,0.722022,0.353693,0.308239
2,0.069464,0.054236,0.982899,0.009873,0.06733,0.39751,0.716272,0.140618,0.261324,0.598681,...,0.624086,0.612425,0.555324,0.372327,0.352403,0.829182,0.769005,0.30285,0.915727,0.744135
3,0.86127,0.40894,0.402715,0.37367,0.581839,0.351824,0.091957,0.87611,0.064662,0.153543,...,0.737523,0.682785,0.415256,0.466336,0.48473,0.400797,0.576846,0.870898,0.919293,0.867805
4,0.978261,0.667928,0.324714,0.450345,0.031644,0.260513,0.687636,0.269007,0.416501,0.729017,...,0.868373,0.707276,0.330724,0.997803,0.0845,0.670043,0.013273,0.546738,0.128899,0.862996

In [27]:
newdf

            0         1         2         3         4
0       Harry  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [28]:
newdf.head()

          0         1         2         3         4
0     Harry  0.794984  0.069464  0.861270  0.978261
1  0.471677  0.396226  0.054236  0.408940  0.667928
2  0.647117  0.400476  0.982899  0.402715  0.324714
3  0.397568  0.782624  0.009873  0.373670  0.450345
4  0.562236  0.487736  0.067330  0.581839  0.031644

In [29]:
newdf.sort_index(axis = 1, ascending= False)

            4         3         2         1         0
0    0.978261  0.861270  0.069464  0.794984     Harry
1    0.667928  0.408940  0.054236  0.396226  0.471677
2    0.324714  0.402715  0.982899  0.400476  0.647117
3    0.450345  0.373670  0.009873  0.782624  0.397568
4    0.031644  0.581839  0.067330  0.487736  0.562236
..        ...       ...       ...       ...       ...
329  0.670043  0.400797  0.829182  0.552123  0.994718
330  0.013273  0.576846  0.769005  0.614810  0.912063
331  0.546738  0.870898  0.302850  0.722022  0.161824
332  0.128899  0.919293  0.915727  0.353693  0.862252
333  0.862996  0.867805  0.744135  0.308239  0.387462

[334 rows x 5 columns]

In [30]:
newdf.head()

          0         1         2         3         4
0     Harry  0.794984  0.069464  0.861270  0.978261
1  0.471677  0.396226  0.054236  0.408940  0.667928
2  0.647117  0.400476  0.982899  0.402715  0.324714
3  0.397568  0.782624  0.009873  0.373670  0.450345
4  0.562236  0.487736  0.067330  0.581839  0.031644

In [31]:
newdf[0]

0         Harry
1      0.471677
2      0.647117
3      0.397568
4      0.562236
         ...
329    0.994718
330    0.912063
331    0.161824
332    0.862252
333    0.387462
Name: 0, Length: 334, dtype: object

In [32]:
type(newdf[0])

pandas.core.series.Series

In [33]:
newdf2 = newdf #ewdf2 is view of newdf

In [34]:
newdf2

            0         1         2         3         4
0       Harry  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [35]:
newdf2[0][0] = 9785

In [36]:
newdf2

            0         1         2         3         4
0        9785  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [37]:
newdf

            0         1         2         3         4
0        9785  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [38]:
newdf2 = newdf.copy() #This wont change when the data in the newdf is changed

In [39]:
newdf2

            0         1         2         3         4
0        9785  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [40]:
newdf.loc[0, 0] = 69

In [41]:
newdf.head(2)

          0         1         2        3         4
0        69  0.794984  0.069464  0.86127  0.978261
1  0.471677  0.396226  0.054236  0.40894  0.667928

In [42]:
newdf.columns = list("ABCDE")

In [43]:
newdf

            A         B         C         D         E
0          69  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [44]:
newdf.head(2)

          A         B         C        D         E
0        69  0.794984  0.069464  0.86127  0.978261
1  0.471677  0.396226  0.054236  0.40894  0.667928

In [45]:
newdf.loc[0, 0] = 34 #as we initialized the columns as ABC now loc will create new to change we have to use ABC now

In [46]:
newdf.head(2)

          A         B         C        D         E     0
0        69  0.794984  0.069464  0.86127  0.978261  34.0
1  0.471677  0.396226  0.054236  0.40894  0.667928   NaN

In [47]:
newdf.loc[0, 'A'] = 420

In [48]:
newdf.head(2)

          A         B         C        D         E     0
0       420  0.794984  0.069464  0.86127  0.978261  34.0
1  0.471677  0.396226  0.054236  0.40894  0.667928   NaN

In [49]:
newdf.drop(0, axis = 1) #It removed that 0th column

            A         B         C         D         E
0         420  0.794984  0.069464  0.861270  0.978261
1    0.471677  0.396226  0.054236  0.408940  0.667928
2    0.647117  0.400476  0.982899  0.402715  0.324714
3    0.397568  0.782624  0.009873  0.373670  0.450345
4    0.562236  0.487736  0.067330  0.581839  0.031644
..        ...       ...       ...       ...       ...
329  0.994718  0.552123  0.829182  0.400797  0.670043
330  0.912063  0.614810  0.769005  0.576846  0.013273
331  0.161824  0.722022  0.302850  0.870898  0.546738
332  0.862252  0.353693  0.915727  0.919293  0.128899
333  0.387462  0.308239  0.744135  0.867805  0.862996

[334 rows x 5 columns]

In [50]:
newdf.loc[[1, 2], ['C', 'D', 'E']]

          C         D         E
1  0.054236  0.408940  0.667928
2  0.982899  0.402715  0.324714

In [51]:
newdf.loc[:, ['C', 'D', 'E']] #: this will give all the rows in this and all the column in the below onw

            C         D         E
0    0.069464  0.861270  0.978261
1    0.054236  0.408940  0.667928
2    0.982899  0.402715  0.324714
3    0.009873  0.373670  0.450345
4    0.067330  0.581839  0.031644
..        ...       ...       ...
329  0.829182  0.400797  0.670043
330  0.769005  0.576846  0.013273
331  0.302850  0.870898  0.546738
332  0.915727  0.919293  0.128899
333  0.744135  0.867805  0.862996

[334 rows x 3 columns]

In [52]:
newdf.loc[[1, 2], :]

          A         B         C         D         E   0
1  0.471677  0.396226  0.054236  0.408940  0.667928 NaN
2  0.647117  0.400476  0.982899  0.402715  0.324714 NaN

In [53]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

            A         B         C         D         E   0
5    0.226655  0.460376  0.397510  0.351824  0.260513 NaN
9    0.262193  0.253001  0.598681  0.153543  0.729017 NaN
12   0.004516  0.627843  0.576789  0.446074  0.035323 NaN
14     0.2339  0.597356  0.447244  0.332846  0.983924 NaN
16   0.196758  0.620239  0.353745  0.281855  0.074288 NaN
..        ...       ...       ...       ...       ...  ..
312  0.227192  0.652247  0.522323  0.556450  0.044315 NaN
319  0.017752  0.358111  0.874042  0.011677  0.755587 NaN
322  0.024623  0.483350  0.618221  0.773368  0.565735 NaN
325  0.135762  0.278809  0.612425  0.682785  0.707276 NaN
331  0.161824  0.722022  0.302850  0.870898  0.546738 NaN

[85 rows x 6 columns]

In [54]:
newdf.iloc[0, 4]

0.9782606282205116

In [55]:
newdf.iloc[[0, 1], [1, 2]]

          B         C
0  0.794984  0.069464
1  0.396226  0.054236

In [56]:
newdf.drop([0, 'A', 'C'], axis = 1)

            B         D         E
0    0.794984  0.861270  0.978261
1    0.396226  0.408940  0.667928
2    0.400476  0.402715  0.324714
3    0.782624  0.373670  0.450345
4    0.487736  0.581839  0.031644
..        ...       ...       ...
329  0.552123  0.400797  0.670043
330  0.614810  0.576846  0.013273
331  0.722022  0.870898  0.546738
332  0.353693  0.919293  0.128899
333  0.308239  0.867805  0.862996

[334 rows x 3 columns]

In [57]:
newdf.drop([2, 329], axis = 0, inplace = True) # you dont have to wroite here newdf = .. to chnage the data frame it use of inplace will change the DataFrame itself

In [58]:
newdf

            A         B         C         D         E     0
0         420  0.794984  0.069464  0.861270  0.978261  34.0
1    0.471677  0.396226  0.054236  0.408940  0.667928   NaN
3    0.397568  0.782624  0.009873  0.373670  0.450345   NaN
4    0.562236  0.487736  0.067330  0.581839  0.031644   NaN
5    0.226655  0.460376  0.397510  0.351824  0.260513   NaN
..        ...       ...       ...       ...       ...   ...
328  0.581591  0.189906  0.352403  0.484730  0.084500   NaN
330  0.912063  0.614810  0.769005  0.576846  0.013273   NaN
331  0.161824  0.722022  0.302850  0.870898  0.546738   NaN
332  0.862252  0.353693  0.915727  0.919293  0.128899   NaN
333  0.387462  0.308239  0.744135  0.867805  0.862996   NaN

[332 rows x 6 columns]

In [59]:
# i wanna retsrat the indexes from 0 to n in the dataframe

In [60]:
newdf.reset_index() #But it will add the column of the original indeces

     index         A         B         C         D         E     0
0        0       420  0.794984  0.069464  0.861270  0.978261  34.0
1        1  0.471677  0.396226  0.054236  0.408940  0.667928   NaN
2        3  0.397568  0.782624  0.009873  0.373670  0.450345   NaN
3        4  0.562236  0.487736  0.067330  0.581839  0.031644   NaN
4        5  0.226655  0.460376  0.397510  0.351824  0.260513   NaN
..     ...       ...       ...       ...       ...       ...   ...
327    328  0.581591  0.189906  0.352403  0.484730  0.084500   NaN
328    330  0.912063  0.614810  0.769005  0.576846  0.013273   NaN
329    331  0.161824  0.722022  0.302850  0.870898  0.546738   NaN
330    332  0.862252  0.353693  0.915727  0.919293  0.128899   NaN
331    333  0.387462  0.308239  0.744135  0.867805  0.862996   NaN

[332 rows x 7 columns]

In [61]:
newdf.reset_index(drop = True)

            A         B         C         D         E     0
0         420  0.794984  0.069464  0.861270  0.978261  34.0
1    0.471677  0.396226  0.054236  0.408940  0.667928   NaN
2    0.397568  0.782624  0.009873  0.373670  0.450345   NaN
3    0.562236  0.487736  0.067330  0.581839  0.031644   NaN
4    0.226655  0.460376  0.397510  0.351824  0.260513   NaN
..        ...       ...       ...       ...       ...   ...
327  0.581591  0.189906  0.352403  0.484730  0.084500   NaN
328  0.912063  0.614810  0.769005  0.576846  0.013273   NaN
329  0.161824  0.722022  0.302850  0.870898  0.546738   NaN
330  0.862252  0.353693  0.915727  0.919293  0.128899   NaN
331  0.387462  0.308239  0.744135  0.867805  0.862996   NaN

[332 rows x 6 columns]

In [62]:
newdf['B'].isnull()

0      False
1      False
3      False
4      False
5      False
       ...
328    False
330    False
331    False
332    False
333    False
Name: B, Length: 332, dtype: bool

In [63]:
newdf['B'] = None

In [64]:
newdf

            A     B         C         D         E     0
0         420  None  0.069464  0.861270  0.978261  34.0
1    0.471677  None  0.054236  0.408940  0.667928   NaN
3    0.397568  None  0.009873  0.373670  0.450345   NaN
4    0.562236  None  0.067330  0.581839  0.031644   NaN
5    0.226655  None  0.397510  0.351824  0.260513   NaN
..        ...   ...       ...       ...       ...   ...
328  0.581591  None  0.352403  0.484730  0.084500   NaN
330  0.912063  None  0.769005  0.576846  0.013273   NaN
331  0.161824  None  0.302850  0.870898  0.546738   NaN
332  0.862252  None  0.915727  0.919293  0.128899   NaN
333  0.387462  None  0.744135  0.867805  0.862996   NaN

[332 rows x 6 columns]

In [65]:
newdf['B'].isnull()

0      True
1      True
3      True
4      True
5      True
       ...
328    True
330    True
331    True
332    True
333    True
Name: B, Length: 332, dtype: bool

In [66]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'Eva', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 65000, 90000, 75000]})

In [67]:
df

      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   65000
3      Eva   32      Houston   90000
4      Eva   29      Phoenix   75000

In [68]:
df.head()

      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   65000
3      Eva   32      Houston   90000
4      Eva   29      Phoenix   75000

In [69]:
df.dropna(how = 'all', axis=1) #as there is no NaN column in this dataframe its not doing anythinf g here

      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   65000
3      Eva   32      Houston   90000
4      Eva   29      Phoenix   75000

In [70]:
df.drop_duplicates(subset = ['Name'])

      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   65000
3      Eva   32      Houston   90000

In [71]:
df.tail(2)

  Name  Age     City  Salary
3  Eva   32  Houston   90000
4  Eva   29  Phoenix   75000

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [73]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  76000.000000
std     3.962323   9617.692031
min    22.000000  65000.000000
25%    24.000000  70000.000000
50%    27.000000  75000.000000
75%    29.000000  80000.000000
max    32.000000  90000.000000

In [74]:
df['Name'].value_counts(dropna = False)

Name
Eva        2
Alice      1
Bob        1
Charlie    1
Name: count, dtype: int64

In [75]:
df.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False  False   False
4  False  False  False   False

In [76]:
  data = pd.read_excel('Book2.xlsx')

In [77]:
data

     Name  Place College
0     Nik  Latur   Bidve
1  Nikhil    KGP  IITKGP

In [78]:
data.iloc[0, 0] = 34

In [79]:
data

     Name  Place College
0      34  Latur   Bidve
1  Nikhil    KGP  IITKGP

In [82]:
data.to_excel('Book2.xlsx', sheet_name = 'sheet2')# it will make the sheet 2 in that excal sheet and copy the data in it

In [84]:
df = data.copy()
with pd.ExcelWriter('Book2.xlsx') as writer:
    data.to_excel(writer, sheet_name = 'Sheet1')
    data.to_excel(writer, sheet_name = 'Sheet2')# To get both the sheets